exclude: ^(tests|docs)/
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7
    hooks:
      - id: uv-lock

  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        files: \.ya?ml$

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.0
    hooks:
      - id: check-jsonschema
        name: Validate RenderCV YAML schema
        files: ^cv/.*\.ya?ml$
        args:
          - --schemafile
          - https://raw.githubusercontent.com/rendercv/rendercv/refs/tags/v2.4/schema.json

