version: '3'

vars:
  CV_FILENAME: Kalinin_Nikita_CV

tasks:
  # ======== Environment ========
  sync:
    desc: Sync dependencies using uv
    cmds:
      - uv sync

  precommit:
    desc: Install git hooks
    deps: [sync]
    cmds:
      - uv run pre-commit install

  init:
    desc: Full project setup
    deps: [sync, precommit]

  # ======== Commitizen ========
  cz-commit:
    desc: Commit using Conventional Commits
    deps: [sync]
    cmds:
      - uv run cz commit

  cz-check:
    desc: Check commit messages
    deps: [sync]
    cmds:
      - uv run cz check

  cz-bump:
    desc: Bump version and update changelog
    deps: [sync]
    cmds:
      - uv run cz bump

  release:
    desc: Bump version and push tags
    deps: [cz-bump]
    cmds:
      - git push --follow-tags

  # ======== RenderCV ========
  cv-render:
    desc: Render CV from YAML to PDF
    deps: [sync]
    cmds:
      - uv run rendercv render cv/data.yaml
        --pdf-path ../output/{{.CV_FILENAME}}.pdf
        --typst-path ../output/{{.CV_FILENAME}}.typ
        --markdown-path ../output/{{.CV_FILENAME}}.md
        --html-path ../output/{{.CV_FILENAME}}.html
        --png-path ../output/
        -nomd -nohtml -nopng

  cv-clean:
    desc: Remove generated build artifacts
    cmds:
      - rm -rf ./output/*

  cv-validate:
    desc: Validate CV YAML against RenderCV JSON Schema
    deps: [sync]
    cmds:
      - >
        uv run check-jsonschema
        --schemafile https://raw.githubusercontent.com/rendercv/rendercv/refs/tags/v2.6/schema.json
        cv/data.yaml

  cv-fmt:
    desc: Format YAML files with yamlfmt
    deps: [sync]
    cmds:
      - task: cv-validate
      - yamlfmt cv/*

